### ISSUE TITLE
Rewrite the JS bindings with JSOO externals

### ISSUE THREAD

**Issue by phated** [grain-lang/binaryen.ml#104]
In Grain, I learned a bit more about how to write JSOO external bindings and it might be better to provide those instead of virtual modules.

**Comment by hhugo** [comment]
Are you thinking about having a single library for both js and native ?

**Comment by phated** [comment]
Yes! This is on my Todo list for a future release. I'm currently focused on trying to support Mac M1, but I'll work on that after.
